### ISSUE TITLE
Request for build script

### ISSUE THREAD

**Issue by yarnball** [gp3gp3gp3/react-jwt-auth#23]
Hi,

This is a really good repo for handling JWT tokens. Your code is very adaptable, and I've set it up with my server.

However, `build` does not create a version I can use on my server.

It seems like bundle & bundle.map are created in a folder (`/public`). I copied these files to my server, but they do not work. I also tried adding the `index.html` file with reference to the `bundle.js` but that did not help.

Could you please help with this?

**Comment by gp3gp3gp3** [comment]
Running `npm start` will start the local server for this repository at localhost.  It's running a small express node server to serve up the pages.  Running `npm build` will create the bundled javascript file with the production version.

If you want to deploy this to heroku you can use `heroku create` and set the created heroku link in your remote links in your git.  But regarding integrating this to however your server is set up isn't something I could answer, since it's your server and I don't know how you've set it up.  If you want to try deploying it to heroku yourself you could clone the repo and follow [these instructions](https://devcenter.heroku.com/articles/git#creating-a-heroku-remote), and then maybe try to see how to integrate it to your server from there?
